language: ruby
sudo: required
rvm:
  - 2.4.4
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
# base env
  # Test latest Puppet 5 version
  - PUPPET=5.5 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Test latest Puppet version
  - PUPPET=6 RUBY_AUGEAS=0.5


matrix:
  fast_finish: true

install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: ""
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.4.4
    condition: "$FORGE_PUBLISH = true"
