language: ruby
rvm:
  - 1.8.7
  - 1.9.3
notifications:
  email:
   - dcleal@redhat.com
   - raphael.pinson@camptocamp.com
env:
# 0.25 cannot pass rspec tests
#  - PUPPET_VERSION=0.25.5
# 0.26 did not support comment for the host type
#  - PUPPET_VERSION=2.6.17
#  - PUPPET_VERSION=2.7.18
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
  - sudo touch /etc/aliases
  - gem install bundler
  - bundle install
